PREFIX ex: <http://example.com/menu#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  ?item rdf:type ex:MenuItem .
  ?item ex:company ?CompanyIRI .
  ?item ex:itemName ?Item .
  ?item ex:category ?Category .
  ?item ex:calories ?Calories .
  ?item ex:totalFat ?Total_Fat_g .
  ?item ex:saturatedFat ?Saturated_Fat_g .
  ?item ex:transFat ?Trans_Fat_g .
  ?item ex:cholesterol ?Cholesterol_mg .
  ?item ex:sodium ?Sodium_mg .
  ?item ex:carbs ?Carbs_g .
  ?item ex:fiber ?Fiber_g .
  ?item ex:sugars ?Sugars_g .
  ?item ex:protein ?Protein_g .
}
WHERE {
  # URI único por fila usando ROWNUM
  BIND(URI(CONCAT("http://example.com/menu/item/", STR(?ROWNUM))) AS ?item)
  
  # Mapear nombre de la compañía a IRI de DBpedia
  BIND(
    IF(?Company = "McDonalds", <http://dbpedia.org/resource/McDonald's>,
    IF(?Company = "Burger_King", <http://dbpedia.org/resource/Burger_King>,
    IF(?Company = "Pizza_Hut", <http://dbpedia.org/resource/Pizza_Hut>,
    IF(?Company = "KFC", <http://dbpedia.org/resource/KFC>,
    IF(?Company = "Taco_Bell", <http://dbpedia.org/resource/Taco_Bell>,
    IF(?Company = "Wendys", <http://dbpedia.org/resource/The_Wendy's_Company>,
    IF(?Company = "Subway", <http://dbpedia.org/resource/Subway_(restaurant)>,
       <http://example.com/menu#UnknownCompany>
    ))))))) AS ?CompanyIRI
  )
  
  # Mapear columnas del CSV a variables SPARQL
  BIND(?Item AS ?Item)
  BIND(?Category AS ?Category)
  BIND(?Calories AS ?Calories)
  BIND(?Total_Fat_g AS ?Total_Fat_g)
  BIND(?Saturated_Fat_g AS ?Saturated_Fat_g)
  BIND(?Trans_Fat_g AS ?Trans_Fat_g)
  BIND(?Cholesterol_mg AS ?Cholesterol_mg)
  BIND(?Sodium_mg AS ?Sodium_mg)
  BIND(?Carbs_g AS ?Carbs_g)
  BIND(?Fiber_g AS ?Fiber_g)
  BIND(?Sugars_g AS ?Sugars_g)
  BIND(?Protein_g AS ?Protein_g)
}